---
# tasks file for ubuntu_postgres
- name: Install packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/pg_hba.conf"

- name: Empty data dir
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: absent

- name: Start and enable service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
