---
# tasks file for ubuntu_app

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable

- name: install docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - containerd.io
    - docker-ce

- name: check docker is active
  service:
    name: docker
    state: started
    enabled: yes
