---
- hosts: centOS_app
  remote_user: andrew
  become: yes
  roles:
    - role: centOS_app

- hosts: ubuntu_app
  remote_user: andrew
  become: yes
  roles:
    - role: ubuntu_app

- hosts: ubuntu_postgres
  remote_user: andrew
  become: yes
  roles:
    - role: ubuntu_postgres
