---
- hosts: all
  remote_user: andrew
  gather_facts: yes
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable

    - name: install docker
      apt:
        name: docker
        state: present
        update_cache: yes
      loop:
        - containerd.io
        - docker-ce
        - docker-ce-cli

    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes
